export const GET_EMPOLYEES="GET_EMPOLYEES";
export const GET_EMPOLYEES_SUCCESS="GET_EMPOLYEES_SUCCESS";
export const GET_EMPOLYEES_ERROR="GET_EMPOLYEES_ERROR"

export const CREATE_EMPOLYEES="CREATE_EMPOLYEES";
export const CREATE_EMPOLYEES_SUCCESS="CREATE_EMPOLYEES_SUCCESS";
export const CREATE_EMPOLYEES_ERROR="CREATE_EMPOLYEES_ERROR"

export const DELETE_EMPOLYEES="DELETE_EMPOLYEES";
export const DELETE_EMPOLYEES_SUCCESS="DELETE_EMPOLYEES_SUCCESS";
export const DELETE_EMPOLYEES_ERROR="DELETE_EMPOLYEES_ERROR"